### ISSUE TITLE
[1.16.1] Crash while shift clicking recipe output from a Crafting Table.

### ISSUE THREAD

**Issue by Gbergz** [MelanX/MoreVanillaLib#15]
Title^

**MoreVanillaLib Version:** 1.2.6
**Forge Version:** 32.0.59
**MC:** 1.16.1

**Crash-Report within logs:** https://hastebin.com/dozulirexo.rb

**Comment by MelanX** [comment]
What was you trying to craft? Other mods in the pack? Complete crash log? A modpack?
Just this doesn’t help. And there is something about JEI: I need JEI version.

**Comment by Gbergz** [comment]
I don't have more information. A user playing my modpack sent me this information.
No crash-report was generated.

User tried to craft Fruit Punch [(Pams Harvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core)

Modpack: [TNP Limitless 3](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3)

JEI Version: 7.0.0.6
Modlist of modpack: https://github.com/The-Nexus-Project/Limitless-3/blob/master/modlist

**Comment by MelanX** [comment]
Do you know if this happened on server or singleplayer? And if server: crashed the server or the client?

**Comment by Gbergz** [comment]
EDIT: It crashed both client & server.

**Comment by MelanX** [comment]
closed by https://github.com/MelanX/MoreVanillaLib/commit/006773d590f0d6333e34378a932b0dd278acd742
