### ISSUE TITLE
Crash when loading a world.

### ISSUE THREAD

**Issue by HarkLight** [MelanX/MoreVanillaLib#16]
Having any 1.16.2 mods (well at least VanillaHammer and more vanilla tools) with the MoreVanillaLib crashes the game when loading a already created world or creating a new world. Crash report and the log of the moment i tried to load a created world:
[2020-08-25-1.log](https://github.com/MelanX/MoreVanillaLib/files/5126731/2020-08-25-1.log)
[crash report.txt](https://github.com/MelanX/MoreVanillaLib/files/5126732/crash.report.txt)

**Comment by MelanX** [comment]
Next time use pastebin, please.

**Comment by MelanX** [comment]
Crash: https://pastebin.com/KWCyPgAD
Log: https://pastebin.com/MxvPfBP7
