### ISSUE TITLE
MoreVanillaLib making my game crash.

### ISSUE THREAD

**Issue by Quearrel** [MelanX/MoreVanillaLib#17]
I recently downloaded this and Vanilla Hammers for 1.16.2, forge version, of course. The game loads up to the main menu, but when i try to enter a world, it crashes. This is the crash report. Please fix this, I would really like to use your mods!
[crash-2020-08-26_22.56.50-client.txt](https://github.com/MelanX/MoreVanillaLib/files/5133908/crash-2020-08-26_22.56.50-client.txt)

**Comment by MelanX** [comment]
I need information about what versions you are using and please post your crash with pastebin.com

**Comment by Quearrel** [comment]
https://pastebin.com/knsZQqA1
The versions I am using are
MorevanillaLib-1.16.2-1.2.10.jar
Vanilla-Hammers-Mod-1.16.2.jar
I am using Minecraft forge for 1.16.2

**Comment by MelanX** [comment]
Should be fixed in next version, I thought I uploaded it. Will upload it this afternoon.

**Comment by Quearrel** [comment]
awesome, thank you!
