### ISSUE TITLE
Mineral Drops bugged?

### ISSUE THREAD

**Issue by TocinoShimmer** [MelanX/MoreVanillaLib#21]
Hello, today i update the "More Vanilla Lib" mod and i wanted to make a "house" for my chickens, but when i use the excavator, this one drops a lot of emeralds. Between 8 and 12 emeralds.

Idk what just happend but the same thing happends with the more vanilla tools. For example, the emerald axe, drops emeralds when u hit a mob, or break any block with it, and the most OP for me at the moment. the diamond excavator... drops 8 diamonds everytime u break blocks like grasss... etc.

Is pretty OP for me and i think is a glitch. Please, fix it

![2021-03-18_19 01 31](https://user-images.githubusercontent.com/56833714/111717094-012baa00-881d-11eb-9b7f-f0c89dc0e102.png)
![2021-03-18_19 01 42](https://user-images.githubusercontent.com/56833714/111717096-025cd700-881d-11eb-84bd-3fa36884a072.png)
![2021-03-18_19 02 59](https://user-images.githubusercontent.com/56833714/111717097-02f56d80-881d-11eb-9f88-986fc87113d1.png)
![2021-03-18_19 03 27](https://user-images.githubusercontent.com/56833714/111717110-08eb4e80-881d-11eb-800c-9422b9eea535.png)
![2021-03-18_19 03 33](https://user-images.githubusercontent.com/56833714/111717114-0983e500-881d-11eb-970c-41d3ee3d5992.png)
![2021-03-18_19 03 59](https://user-images.githubusercontent.com/56833714/111717115-0a1c7b80-881d-11eb-98c7-13ada07ab73d.png)
![2021-03-18_19 04 05](https://user-images.githubusercontent.com/56833714/111717116-0a1c7b80-881d-11eb-8a91-e5add4b70dca.png)

**Comment by MelanX** [comment]
#22
