### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by MelanX** [MelanX/MoreVanillaLib#24]
I want to change to license from MIT License to Apache 2.0 License. More information can be found here: https://www.apache.org/licenses/LICENSE-2.0.txt

Before I change it, I need all permissions from all contributors of this project. All the users below, do you agree the change to Apache 2.0?
@MelanX 
@TheDirectorX

**Comment by MelanX** [comment]
Yes, I do

**Comment by TheDirectorX** [comment]
Yep.
