### ISSUE TITLE
Console spam bug

### ISSUE THREAD

**Issue by EvilEtho** [MelanX/MoreVanillaLib#26]
### Minecraft version

1.18.1

### MoreVanillaLib version

1.18.1-3.0.3

### Forge version

39.0.19

### The latest.log file

https://pastebin.com/n0Pb4u7f

### Issue description

This keeps getting spammed on my server console. https://pastebin.com/n0Pb4u7f

**Comment by MelanX** [comment]
Looks like other mods as cyclic, roots and allthemodium do spam that, too. Looks like a Forge problem to me. Will look at it a bit better lateral. Thank you!
Was that in a public modpack? If yes, which version? If not, could you do `/libx modlist` ingame, Click on the result and put it in here? Thank you!
