### ISSUE TITLE
Night Config

### ISSUE THREAD

**Issue by Anxly** [MelanX/MoreVanillaLib#29]
### Minecraft version

1.19.4

### MoreVanillaLib version

1.16.4-1.4.1

### Main extension mod

Vanilla Hammers [Forge]

### Forge version

36.2.34

### The latest.log file

https://pastebin.com/iEQBhD58

### Issue description

When starting minecraft MoreVanillaLib gives this error: com.electronwill.nightconfig.parsingexception .
![image](https://github.com/MelanX/MoreVanillaLib/assets/102521783/e2088758-ed06-467f-b9e1-93b1b767fcd7)

### Steps to reproduce

1. Start Minecraft
2. U get this error

### Other information

I tried some things, like i used more ram, uninstalled java, used a mod for Night config, but nothing seemed to work.

**Comment by MelanX** [comment]
You’re using a version for 1.16.4 as the version name of the mod says, try with a version for 1.19.4
