### ISSUE TITLE
No "Luck Of Cheap Repairing" Enchant

### ISSUE THREAD

**Issue by Faylen** [MelanX/MoreVanillaLib#30]
Minecraft version
1.19.2

MoreVanillaLib version
1.19.1-4.1.1

Mod:
Tried with just the library mod as I'm interested in Luck of Cheap repairing only, but even trying with the More Vanilla Tools & Simply Tools mods it didn't work.

Forge version
43.2.10

Issue description
You can't get luck of cheap repairing..... The enchant doesn't show up at all. Both the other main mods work just fine and show their added items, but not the enchant :/

**Comment by MelanX** [comment]
I saw that I removed it during the 1.19 port. It was definitely intentional. I didn't like the enchantment anymore, so it's gone. Sorry to disappoint you.
